development: &default
  adapter: postgresql
  database: slacks_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 10
  timeout: 5000

test:
  <<: *default
  database: slacks_test
